version: "3.7"
services:
    node:
        container_name: goel_box
        image: goel_website
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080"
        working_dir: /app

